require('dotenv').config({ path: require('path').resolve(__dirname, '..', '.env') });
const { PrismaClient } = require('@prisma/client');
const { Pool } = require('pg');
const { PrismaPg } = require('@prisma/adapter-pg');
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const parkingData = [
  // ─── KATHMANDU — PAID ─────────────────────────────────────
  {
    name: "Thamel Chowk Parking",
    address: "Thamel Marg, Thamel, Kathmandu",
    district: "Kathmandu",
    description: "Central Thamel parking near the main intersection. Open-air lot with guard.",
    type: "PAID",
    totalSlots: 25,
    availableSlots: 8,
    bikeRate: 20,
    carRate: 50,
    pricePerHour: 50,
    vehicleType: ["BIKE", "CAR"],
    openHours: "6:00 AM - 10:00 PM",
    lat: 27.71530,
    lng: 85.31230,
  },
  {
    name: "New Road Underground Parking",
    address: "New Road, Kathmandu",
    district: "Kathmandu",
    description: "Large underground multi-level parking facility at New Road gate.",
    type: "PAID",
    totalSlots: 120,
    availableSlots: 35,
    bikeRate: 15,
    carRate: 60,
    pricePerHour: 60,
    vehicleType: ["BIKE", "CAR"],
    openHours: "5:00 AM - 11:00 PM",
    lat: 27.70300,
    lng: 85.31230,
  },
  {
    name: "Durbarmarg Tower Parking",
    address: "Durbarmarg, Kathmandu",
    district: "Kathmandu",
    description: "Multi-story car park behind Durbarmarg commercial strip.",
    type: "PAID",
    totalSlots: 80,
    availableSlots: 22,
    bikeRate: 20,
    carRate: 80,
    pricePerHour: 80,
    vehicleType: ["BIKE", "CAR"],
    openHours: "24 hours",
    lat: 27.71180,
    lng: 85.31680,
  },
  {
    name: "Putalisadak Parking Complex",
    address: "Putalisadak, Kathmandu",
    district: "Kathmandu",
    description: "Commercial parking near Putalisadak intersection.",
    type: "PAID",
    totalSlots: 40,
    availableSlots: 12,
    bikeRate: 15,
    carRate: 40,
    pricePerHour: 40,
    vehicleType: ["BIKE", "CAR"],
    openHours: "6:00 AM - 9:00 PM",
    lat: 27.70620,
    lng: 85.32100,
  },
  {
    name: "Lazimpat Embassy Road Parking",
    address: "Lazimpat, Kathmandu",
    district: "Kathmandu",
    description: "Secure parking near embassies, guarded 24/7.",
    type: "PAID",
    totalSlots: 30,
    availableSlots: 10,
    bikeRate: 25,
    carRate: 70,
    pricePerHour: 70,
    vehicleType: ["BIKE", "CAR"],
    openHours: "24 hours",
    lat: 27.72100,
    lng: 85.31900,
  },
  {
    name: "Boudhanath Stupa Parking",
    address: "Boudhanath, Kathmandu",
    district: "Kathmandu",
    description: "Main parking yard near Boudhanath Stupa entrance.",
    type: "PAID",
    totalSlots: 60,
    availableSlots: 18,
    bikeRate: 15,
    carRate: 40,
    pricePerHour: 40,
    vehicleType: ["BIKE", "CAR"],
    openHours: "5:00 AM - 9:00 PM",
    lat: 27.72150,
    lng: 85.36200,
  },
  {
    name: "Swayambhunath Hill Parking",
    address: "Swayambhunath, Kathmandu",
    district: "Kathmandu",
    description: "Open lot at the base of Swayambhunath (Monkey Temple).",
    type: "PAID",
    totalSlots: 45,
    availableSlots: 20,
    bikeRate: 10,
    carRate: 30,
    pricePerHour: 30,
    vehicleType: ["BIKE", "CAR"],
    openHours: "6:00 AM - 7:00 PM",
    lat: 27.71470,
    lng: 85.29030,
  },
  {
    name: "Pashupatinath Temple Parking",
    address: "Pashupatinath, Kathmandu",
    district: "Kathmandu",
    description: "Official parking area at Pashupatinath Temple complex.",
    type: "PAID",
    totalSlots: 100,
    availableSlots: 30,
    bikeRate: 10,
    carRate: 40,
    pricePerHour: 40,
    vehicleType: ["BIKE", "CAR"],
    openHours: "4:00 AM - 9:00 PM",
    lat: 27.71060,
    lng: 85.34870,
  },
  {
    name: "Baluwatar Parking Zone",
    address: "Baluwatar, Kathmandu",
    district: "Kathmandu",
    description: "Roadside designated parking near Baluwatar residences.",
    type: "PAID",
    totalSlots: 20,
    availableSlots: 7,
    bikeRate: 15,
    carRate: 50,
    pricePerHour: 50,
    vehicleType: ["BIKE", "CAR"],
    openHours: "7:00 AM - 8:00 PM",
    lat: 27.72600,
    lng: 85.33000,
  },
  {
    name: "Kalanki Bus Park Parking",
    address: "Kalanki, Kathmandu",
    district: "Kathmandu",
    description: "Large parking area near Kalanki chowk bus station.",
    type: "PAID",
    totalSlots: 70,
    availableSlots: 25,
    bikeRate: 10,
    carRate: 30,
    pricePerHour: 30,
    vehicleType: ["BIKE", "CAR"],
    openHours: "24 hours",
    lat: 27.69370,
    lng: 85.28150,
  },
  {
    name: "Baneshwor Chowk Parking",
    address: "Baneshwor, Kathmandu",
    district: "Kathmandu",
    description: "Multi-level commercial parking at Baneshwor intersection.",
    type: "PAID",
    totalSlots: 50,
    availableSlots: 15,
    bikeRate: 15,
    carRate: 40,
    pricePerHour: 40,
    vehicleType: ["BIKE", "CAR"],
    openHours: "6:00 AM - 10:00 PM",
    lat: 27.69050,
    lng: 85.34150,
  },
  {
    name: "Maharajgunj Parking Lot",
    address: "Maharajgunj, Kathmandu",
    district: "Kathmandu",
    description: "Open-air parking near Maharajgunj commercial area.",
    type: "PAID",
    totalSlots: 35,
    availableSlots: 14,
    bikeRate: 15,
    carRate: 40,
    pricePerHour: 40,
    vehicleType: ["BIKE", "CAR"],
    openHours: "6:00 AM - 9:00 PM",
    lat: 27.73500,
    lng: 85.33400,
  },
  {
    name: "Chabahil Chowk Parking",
    address: "Chabahil, Kathmandu",
    district: "Kathmandu",
    description: "Open-air parking near Chabahil stupa area.",
    type: "PAID",
    totalSlots: 30,
    availableSlots: 10,
    bikeRate: 10,
    carRate: 30,
    pricePerHour: 30,
    vehicleType: ["BIKE", "CAR"],
    openHours: "6:00 AM - 9:00 PM",
    lat: 27.71700,
    lng: 85.34600,
  },
  {
    name: "Basantapur Tower Parking",
    address: "Basantapur, Kathmandu",
    district: "Kathmandu",
    description: "Compact lot beside Basantapur Durbar Square entrance.",
    type: "PAID",
    totalSlots: 15,
    availableSlots: 3,
    bikeRate: 20,
    carRate: 50,
    pricePerHour: 50,
    vehicleType: ["BIKE", "CAR"],
    openHours: "7:00 AM - 8:00 PM",
    lat: 27.70450,
    lng: 85.30700,
  },
  {
    name: "Ason Chowk Bike Parking",
    address: "Ason, Kathmandu",
    district: "Kathmandu",
    description: "Bikes-only parking in narrow Ason bazaar area.",
    type: "PAID",
    totalSlots: 40,
    availableSlots: 12,
    bikeRate: 10,
    carRate: null,
    pricePerHour: 10,
    vehicleType: ["BIKE"],
    openHours: "6:00 AM - 8:00 PM",
    lat: 27.70800,
    lng: 85.31100,
  },
  {
    name: "Koteshwor Parking Zone",
    address: "Koteshwor, Kathmandu",
    district: "Kathmandu",
    description: "Designated parking area near Koteshwor intersection.",
    type: "PAID",
    totalSlots: 55,
    availableSlots: 20,
    bikeRate: 10,
    carRate: 30,
    pricePerHour: 30,
    vehicleType: ["BIKE", "CAR"],
    openHours: "6:00 AM - 10:00 PM",
    lat: 27.67880,
    lng: 85.34920,
  },
  {
    name: "Gaushala Parking Yard",
    address: "Gaushala, Kathmandu",
    district: "Kathmandu",
    description: "Open lot near Gaushala bus stop and Pashupatinath area.",
    type: "PAID",
    totalSlots: 35,
    availableSlots: 15,
    bikeRate: 10,
    carRate: 30,
    pricePerHour: 30,
    vehicleType: ["BIKE", "CAR"],
    openHours: "5:00 AM - 9:00 PM",
    lat: 27.71100,
    lng: 85.34300,
  },
  {
    name: "Sundhara Commercial Parking",
    address: "Sundhara, Kathmandu",
    district: "Kathmandu",
    description: "Commercial parking facility near Sundhara fountain area.",
    type: "PAID",
    totalSlots: 30,
    availableSlots: 8,
    bikeRate: 15,
    carRate: 50,
    pricePerHour: 50,
    vehicleType: ["BIKE", "CAR"],
    openHours: "6:00 AM - 9:00 PM",
    lat: 27.70000,
    lng: 85.31300,
  },
  {
    name: "Tripureshwor Parking Lot",
    address: "Tripureshwor, Kathmandu",
    district: "Kathmandu",
    description: "Near National Trading Corporation, open-air parking.",
    type: "PAID",
    totalSlots: 45,
    availableSlots: 18,
    bikeRate: 15,
    carRate: 40,
    pricePerHour: 40,
    vehicleType: ["BIKE", "CAR"],
    openHours: "6:00 AM - 9:00 PM",
    lat: 27.69700,
    lng: 85.31100,
  },
  {
    name: "Battisputali Parking",
    address: "Battisputali, Kathmandu",
    district: "Kathmandu",
    description: "Parking lot near Battisputali residential area.",
    type: "PAID",
    totalSlots: 25,
    availableSlots: 10,
    bikeRate: 10,
    carRate: 30,
    pricePerHour: 30,
    vehicleType: ["BIKE", "CAR"],
    openHours: "6:00 AM - 9:00 PM",
    lat: 27.69800,
    lng: 85.33600,
  },

  // ─── KATHMANDU — FREE ─────────────────────────────────────
  {
    name: "Ratna Park Open Ground",
    address: "Ratna Park, Kathmandu",
    district: "Kathmandu",
    description: "Free public parking at Ratna Park open ground area.",
    type: "FREE",
    totalSlots: 30,
    availableSlots: 10,
    bikeRate: 0,
    carRate: 0,
    pricePerHour: 0,
    vehicleType: ["BIKE", "CAR"],
    openHours: "6:00 AM - 8:00 PM",
    lat: 27.70390,
    lng: 85.31550,
  },
  {
    name: "Tundikhel East Side Parking",
    address: "Tundikhel, Kathmandu",
    district: "Kathmandu",
    description: "Free roadside parking along the east side of Tundikhel parade ground.",
    type: "FREE",
    totalSlots: 50,
    availableSlots: 20,
    bikeRate: 0,
    carRate: 0,
    pricePerHour: 0,
    vehicleType: ["BIKE", "CAR"],
    openHours: "24 hours",
    lat: 27.70200,
    lng: 85.31700,
  },
  {
    name: "Kirtipur Old Town Roadside",
    address: "Kirtipur, Kathmandu",
    district: "Kathmandu",
    description: "Free parking along Kirtipur main road near the old town.",
    type: "FREE",
    totalSlots: 20,
    availableSlots: 12,
    bikeRate: 0,
    carRate: 0,
    pricePerHour: 0,
    vehicleType: ["BIKE", "CAR"],
    openHours: "24 hours",
    lat: 27.67850,
    lng: 85.27750,
  },
  {
    name: "Gongabu Bus Park Free Zone",
    address: "Gongabu, Kathmandu",
    district: "Kathmandu",
    description: "Free bike parking near Gongabu new bus park.",
    type: "FREE",
    totalSlots: 40,
    availableSlots: 15,
    bikeRate: 0,
    carRate: 0,
    pricePerHour: 0,
    vehicleType: ["BIKE"],
    openHours: "5:00 AM - 10:00 PM",
    lat: 27.73250,
    lng: 85.31500,
  },
  {
    name: "Balaju Industrial Free Stand",
    address: "Balaju, Kathmandu",
    district: "Kathmandu",
    description: "Free parking near Balaju industrial district.",
    type: "FREE",
    totalSlots: 25,
    availableSlots: 10,
    bikeRate: 0,
    carRate: 0,
    pricePerHour: 0,
    vehicleType: ["BIKE", "CAR"],
    openHours: "6:00 AM - 8:00 PM",
    lat: 27.73100,
    lng: 85.30200,
  },

  // ─── KATHMANDU — GOVERNMENT ───────────────────────────────
  {
    name: "Singha Durbar Govt Parking",
    address: "Singha Durbar, Kathmandu",
    district: "Kathmandu",
    description: "Government designated parking at Singha Durbar complex. ID required.",
    type: "GOVERNMENT",
    totalSlots: 200,
    availableSlots: 60,
    bikeRate: 0,
    carRate: 0,
    pricePerHour: 0,
    vehicleType: ["BIKE", "CAR"],
    openHours: "10:00 AM - 5:00 PM (Weekdays)",
    lat: 27.69900,
    lng: 85.32100,
  },
  {
    name: "Babarmahal Municipal Parking",
    address: "Babarmahal, Kathmandu",
    district: "Kathmandu",
    description: "Kathmandu Metropolitan managed public parking.",
    type: "GOVERNMENT",
    totalSlots: 60,
    availableSlots: 20,
    bikeRate: 5,
    carRate: 15,
    pricePerHour: 15,
    vehicleType: ["BIKE", "CAR"],
    openHours: "7:00 AM - 7:00 PM",
    lat: 27.69400,
    lng: 85.32700,
  },
  {
    name: "Ranipokhari Government Lot",
    address: "Ranipokhari, Kathmandu",
    district: "Kathmandu",
    description: "Government managed parking area near Ranipokhari.",
    type: "GOVERNMENT",
    totalSlots: 40,
    availableSlots: 15,
    bikeRate: 5,
    carRate: 10,
    pricePerHour: 10,
    vehicleType: ["BIKE", "CAR"],
    openHours: "6:00 AM - 8:00 PM",
    lat: 27.70800,
    lng: 85.31500,
  },

  // ─── LALITPUR — PAID ──────────────────────────────────────
  {
    name: "Patan Durbar Square Parking",
    address: "Patan Durbar Square, Lalitpur",
    district: "Lalitpur",
    description: "Main parking for Patan Durbar Square visitors.",
    type: "PAID",
    totalSlots: 35,
    availableSlots: 8,
    bikeRate: 15,
    carRate: 40,
    pricePerHour: 40,
    vehicleType: ["BIKE", "CAR"],
    openHours: "6:00 AM - 8:00 PM",
    lat: 27.67260,
    lng: 85.32530,
  },
  {
    name: "Jawalakhel Parking Complex",
    address: "Jawalakhel, Lalitpur",
    district: "Lalitpur",
    description: "Near Jawalakhel zoo and commercial area.",
    type: "PAID",
    totalSlots: 40,
    availableSlots: 14,
    bikeRate: 15,
    carRate: 40,
    pricePerHour: 40,
    vehicleType: ["BIKE", "CAR"],
    openHours: "6:00 AM - 9:00 PM",
    lat: 27.67310,
    lng: 85.31940,
  },
  {
    name: "Pulchowk Engineering Parking",
    address: "Pulchowk, Lalitpur",
    district: "Lalitpur",
    description: "Parking near IOE Pulchowk campus gate.",
    type: "PAID",
    totalSlots: 30,
    availableSlots: 12,
    bikeRate: 10,
    carRate: 30,
    pricePerHour: 30,
    vehicleType: ["BIKE", "CAR"],
    openHours: "6:00 AM - 8:00 PM",
    lat: 27.68100,
    lng: 85.31800,
  },
  {
    name: "Lagankhel Bus Park Parking",
    address: "Lagankhel, Lalitpur",
    district: "Lalitpur",
    description: "Large parking area at Lagankhel bus terminal.",
    type: "PAID",
    totalSlots: 50,
    availableSlots: 20,
    bikeRate: 10,
    carRate: 30,
    pricePerHour: 30,
    vehicleType: ["BIKE", "CAR"],
    openHours: "5:00 AM - 10:00 PM",
    lat: 27.66800,
    lng: 85.32300,
  },
  {
    name: "Kupondole Parking Zone",
    address: "Kupondole, Lalitpur",
    district: "Lalitpur",
    description: "Roadside designated parking on Kupondole Height.",
    type: "PAID",
    totalSlots: 20,
    availableSlots: 6,
    bikeRate: 15,
    carRate: 40,
    pricePerHour: 40,
    vehicleType: ["BIKE", "CAR"],
    openHours: "7:00 AM - 9:00 PM",
    lat: 27.68600,
    lng: 85.31400,
  },
  {
    name: "Satdobato Commercial Parking",
    address: "Satdobato, Lalitpur",
    district: "Lalitpur",
    description: "Large commercial parking near Ring Road junction.",
    type: "PAID",
    totalSlots: 60,
    availableSlots: 25,
    bikeRate: 10,
    carRate: 30,
    pricePerHour: 30,
    vehicleType: ["BIKE", "CAR"],
    openHours: "6:00 AM - 10:00 PM",
    lat: 27.65500,
    lng: 85.32600,
  },
  {
    name: "Jhamsikhel Parking Lot",
    address: "Jhamsikhel, Lalitpur",
    district: "Lalitpur",
    description: "Parking near Jhamsikhel restaurants and cafes.",
    type: "PAID",
    totalSlots: 25,
    availableSlots: 8,
    bikeRate: 15,
    carRate: 50,
    pricePerHour: 50,
    vehicleType: ["BIKE", "CAR"],
    openHours: "7:00 AM - 10:00 PM",
    lat: 27.67700,
    lng: 85.31600,
  },
  {
    name: "Imadol Parking Zone",
    address: "Imadol, Lalitpur",
    district: "Lalitpur",
    description: "Open parking lot near Imadol residential area.",
    type: "PAID",
    totalSlots: 30,
    availableSlots: 15,
    bikeRate: 10,
    carRate: 25,
    pricePerHour: 25,
    vehicleType: ["BIKE", "CAR"],
    openHours: "6:00 AM - 9:00 PM",
    lat: 27.66100,
    lng: 85.33700,
  },

  // ─── LALITPUR — FREE ──────────────────────────────────────
  {
    name: "Patan Dhoka Free Stand",
    address: "Patan Dhoka, Lalitpur",
    district: "Lalitpur",
    description: "Free bike and car parking at Patan Dhoka gate area.",
    type: "FREE",
    totalSlots: 15,
    availableSlots: 9,
    bikeRate: 0,
    carRate: 0,
    pricePerHour: 0,
    vehicleType: ["BIKE", "CAR"],
    openHours: "24 hours",
    lat: 27.68180,
    lng: 85.31470,
  },
  {
    name: "Mangal Bazaar Roadside",
    address: "Mangal Bazaar, Lalitpur",
    district: "Lalitpur",
    description: "Free roadside parking at Mangal Bazaar area.",
    type: "FREE",
    totalSlots: 12,
    availableSlots: 4,
    bikeRate: 0,
    carRate: 0,
    pricePerHour: 0,
    vehicleType: ["BIKE"],
    openHours: "24 hours",
    lat: 27.67400,
    lng: 85.32600,
  },
  {
    name: "Sanepa Community Parking",
    address: "Sanepa, Lalitpur",
    district: "Lalitpur",
    description: "Community-maintained free parking area in Sanepa.",
    type: "FREE",
    totalSlots: 15,
    availableSlots: 7,
    bikeRate: 0,
    carRate: 0,
    pricePerHour: 0,
    vehicleType: ["BIKE", "CAR"],
    openHours: "24 hours",
    lat: 27.68400,
    lng: 85.30800,
  },

  // ─── LALITPUR — GOVERNMENT ────────────────────────────────
  {
    name: "Lalitpur Metro Civic Parking",
    address: "Pulchowk, Lalitpur",
    district: "Lalitpur",
    description: "Lalitpur Metropolitan City managed public parking.",
    type: "GOVERNMENT",
    totalSlots: 50,
    availableSlots: 20,
    bikeRate: 5,
    carRate: 10,
    pricePerHour: 10,
    vehicleType: ["BIKE", "CAR"],
    openHours: "7:00 AM - 6:00 PM",
    lat: 27.68000,
    lng: 85.31700,
  },

  // ─── BHAKTAPUR — PAID ─────────────────────────────────────
  {
    name: "Bhaktapur Durbar Square Lot",
    address: "Durbar Square, Bhaktapur",
    district: "Bhaktapur",
    description: "Visitor parking near Bhaktapur Durbar Square entrance.",
    type: "PAID",
    totalSlots: 40,
    availableSlots: 15,
    bikeRate: 15,
    carRate: 40,
    pricePerHour: 40,
    vehicleType: ["BIKE", "CAR"],
    openHours: "6:00 AM - 8:00 PM",
    lat: 27.67200,
    lng: 85.42800,
  },
  {
    name: "Suryabinayak Parking",
    address: "Suryabinayak, Bhaktapur",
    district: "Bhaktapur",
    description: "Parking near Suryabinayak temple and Ring Road junction.",
    type: "PAID",
    totalSlots: 35,
    availableSlots: 18,
    bikeRate: 10,
    carRate: 25,
    pricePerHour: 25,
    vehicleType: ["BIKE", "CAR"],
    openHours: "6:00 AM - 9:00 PM",
    lat: 27.66700,
    lng: 85.41000,
  },
  {
    name: "Kamal Binayak Parking Yard",
    address: "Kamal Binayak, Bhaktapur",
    district: "Bhaktapur",
    description: "Open parking near Kamal Binayak area.",
    type: "PAID",
    totalSlots: 30,
    availableSlots: 12,
    bikeRate: 10,
    carRate: 25,
    pricePerHour: 25,
    vehicleType: ["BIKE", "CAR"],
    openHours: "6:00 AM - 8:00 PM",
    lat: 27.67100,
    lng: 85.42200,
  },
  {
    name: "Changunarayan Road Parking",
    address: "Changunarayan, Bhaktapur",
    district: "Bhaktapur",
    description: "Parking near Changunarayan temple hilltop.",
    type: "PAID",
    totalSlots: 20,
    availableSlots: 12,
    bikeRate: 10,
    carRate: 20,
    pricePerHour: 20,
    vehicleType: ["BIKE", "CAR"],
    openHours: "6:00 AM - 6:00 PM",
    lat: 27.70900,
    lng: 85.42700,
  },
  {
    name: "Thimi Parking Zone",
    address: "Thimi, Bhaktapur",
    district: "Bhaktapur",
    description: "Designated parking in Thimi town center.",
    type: "PAID",
    totalSlots: 25,
    availableSlots: 10,
    bikeRate: 10,
    carRate: 25,
    pricePerHour: 25,
    vehicleType: ["BIKE", "CAR"],
    openHours: "6:00 AM - 8:00 PM",
    lat: 27.67500,
    lng: 85.38900,
  },
  {
    name: "Lokanthali Parking Area",
    address: "Lokanthali, Bhaktapur",
    district: "Bhaktapur",
    description: "Parking on the highway near Lokanthali.",
    type: "PAID",
    totalSlots: 30,
    availableSlots: 14,
    bikeRate: 10,
    carRate: 20,
    pricePerHour: 20,
    vehicleType: ["BIKE", "CAR"],
    openHours: "24 hours",
    lat: 27.67300,
    lng: 85.37500,
  },

  // ─── BHAKTAPUR — FREE ─────────────────────────────────────
  {
    name: "Dattatreya Square Free Stand",
    address: "Dattatreya Square, Bhaktapur",
    district: "Bhaktapur",
    description: "Free bike parking at Dattatreya Square.",
    type: "FREE",
    totalSlots: 15,
    availableSlots: 8,
    bikeRate: 0,
    carRate: 0,
    pricePerHour: 0,
    vehicleType: ["BIKE"],
    openHours: "24 hours",
    lat: 27.67300,
    lng: 85.43100,
  },
  {
    name: "Pottery Square Roadside",
    address: "Pottery Square, Bhaktapur",
    district: "Bhaktapur",
    description: "Free roadside parking near famous Pottery Square.",
    type: "FREE",
    totalSlots: 10,
    availableSlots: 5,
    bikeRate: 0,
    carRate: 0,
    pricePerHour: 0,
    vehicleType: ["BIKE"],
    openHours: "24 hours",
    lat: 27.67150,
    lng: 85.42700,
  },
  {
    name: "Sallaghari Free Zone",
    address: "Sallaghari, Bhaktapur",
    district: "Bhaktapur",
    description: "Free parking area near Sallaghari junction.",
    type: "FREE",
    totalSlots: 20,
    availableSlots: 10,
    bikeRate: 0,
    carRate: 0,
    pricePerHour: 0,
    vehicleType: ["BIKE", "CAR"],
    openHours: "24 hours",
    lat: 27.67200,
    lng: 85.41500,
  },

  // ─── BHAKTAPUR — GOVERNMENT ───────────────────────────────
  {
    name: "Bhaktapur Municipality Parking",
    address: "Municipal Office, Bhaktapur",
    district: "Bhaktapur",
    description: "Municipality-managed public parking in Bhaktapur.",
    type: "GOVERNMENT",
    totalSlots: 35,
    availableSlots: 15,
    bikeRate: 5,
    carRate: 10,
    pricePerHour: 10,
    vehicleType: ["BIKE", "CAR"],
    openHours: "7:00 AM - 6:00 PM",
    lat: 27.67100,
    lng: 85.42900,
  },
];

async function main() {
  console.log('🅿️  Seeding Chowk parking database...\n');

  // Clear existing data
  await prisma.parkingLocation.deleteMany();
  console.log('  ✓ Cleared existing parking locations');

  // Create all parking locations
  let count = 0;
  for (const spot of parkingData) {
    await prisma.parkingLocation.create({ data: spot });
    count++;
  }

  console.log(`  ✓ Seeded ${count} parking locations`);

  // Print summary
  const stats = await prisma.$queryRaw`
    SELECT type, COUNT(*)::int as count, SUM("totalSlots")::int as total_slots 
    FROM "ParkingLocation" 
    GROUP BY type
  `;
  console.log('\n  📊 Summary:');
  for (const row of stats) {
    console.log(`     ${row.type}: ${row.count} locations, ${row.total_slots} total slots`);
  }

  const districts = await prisma.$queryRaw`
    SELECT district, COUNT(*)::int as count
    FROM "ParkingLocation"
    GROUP BY district
  `;
  console.log('\n  🗺️  Districts:');
  for (const row of districts) {
    console.log(`     ${row.district}: ${row.count} locations`);
  }

  console.log('\n✅ Seed complete!');
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
